import { LegalPage } from '../../modules/legal-page/legal-page.model';
import { TLegalPageInput } from '../../modules/legal-page/legal-page.type';

/**
 * The copy below describes what this application actually does, verified
 * against the code rather than adapted from a template:
 *
 *  - Booking form  -> booking.model.ts      (name, email, phone, company,
 *                                            industry, timeline, preferred
 *                                            date/time, message)
 *  - Contact form  -> contact-message.model.ts (name, email, phone, subject,
 *                                            message)
 *  - Request logs  -> log.middleware.ts, mounted at app.ts:82 (IP, user agent,
 *                                            URL, method, status) with a
 *                                            90-day TTL index
 *  - Admin cookie  -> tc_admin_access, staff only, never set for visitors
 *  - No analytics, tag manager, ad pixels or Firebase are loaded
 *    (NEXT_PUBLIC_ENABLE_ANALYTICS=false; no tracker scripts in the bundle)
 *  - Data lives on Twelve Creative's own VPS in a self-hosted MongoDB
 *
 * ⚠️ Keep this file in step with the code. If data collection changes —
 * a new form field, an analytics script, a third-party processor — update
 * the copy here and re-run the seed, or the policy becomes inaccurate.
 *
 * ⚠️ Written to be accurate and professional, but it is not legal advice.
 * Have counsel review it, and confirm the governing-law and company-details
 * lines, before treating it as a binding commitment.
 */

const EFFECTIVE_DATE = new Date('2026-07-31T00:00:00.000Z');

const PRIVACY_POLICY_MARKDOWN = `Twelve Creative ("we", "us") builds positioning, creative, distribution and
marketing systems for businesses. This policy explains what we collect through
**twelvecreative.io**, why we collect it, and what you can ask us to do with it.

We have deliberately kept this site simple: there is no advertising network, no
tag manager and no cross-site tracking of any kind.

## Information you give us

We only collect what you type into one of our two forms.

**Booking request** — your name, email address, phone number, company name, the
industry you selected, your timeline, your preferred date and time, and any
message you add.

**Contact message** — your name, email address, phone number, subject and
message.

Both forms are optional. You can reach us by email instead and share only what
you choose.

## Information collected automatically

Our server keeps a short technical log of requests to the site, containing the
IP address, browser user-agent string, the URL requested, the HTTP method and
the response status. These records are deleted automatically after 90 days.

We use them to keep the site online, investigate errors and detect abuse such
as automated form spam. They are not used to build a profile of you and are not
combined with the information you submit through a form.

## Cookies

We do not use advertising, analytics or profiling cookies.

The only cookie this site sets is a sign-in cookie for Twelve Creative staff
using the admin area. It is never set for ordinary visitors, and it exists only
to keep an authenticated session open.

Because we set no tracking cookies, there is no consent banner to dismiss.

## Why we use your information

- To reply to your enquiry and arrange a conversation.
- To provide the services you ask us for.
- To keep the site secure, available and free from abuse.
- To meet our legal and accounting obligations.

Where the UK/EU GDPR applies, we rely on your consent when you submit a form,
and on our legitimate interest in responding to enquiries, securing our systems
and running our business.

## How long we keep it

- **Booking requests and contact messages** — kept while we are in contact and
  for as long as we may need them for our business records. Ask us and we will
  delete yours.
- **Technical request logs** — deleted automatically after 90 days.

## Who we share it with

We do not sell your information, and we do not share it for advertising.

We share it only where we have to in order to operate:

- **Our email provider**, to deliver the notification generated by your form
  submission and to reply to you.
- **Our hosting provider**, which runs the server the site and database sit on.
- **Professional advisers or authorities**, where the law requires it.

Your information is stored in our own database on our own server rather than in
a third-party marketing or CRM platform.

## Security

The site is served over HTTPS. Administrative access requires a password and is
restricted to Twelve Creative staff; passwords are stored hashed, never in plain
text. Uploaded files are sanitised before they are stored. Backups of the
database and uploaded media are taken daily and kept on the same server
infrastructure.

No system can be guaranteed completely secure, but we take these steps to
reduce risk.

## Your rights

Depending on where you live, you may have the right to:

- ask for a copy of the information we hold about you;
- ask us to correct it if it is wrong;
- ask us to delete it;
- object to or restrict how we use it;
- withdraw consent you previously gave.

Email us and we will action your request. We will not charge you for it or
treat you differently for asking.

## Children

This site is intended for businesses and is not directed at children. We do not
knowingly collect information from anyone under 16.

## International transfers

We are based in the United States. If you contact us from elsewhere, your
information will be processed in the United States.

## Changes

If we change how we handle your information, we will update this page and the
effective date shown above.

## Contact us

Questions, or want your information removed?

**Email:** hello@twelvecreative.io
**Twelve Creative**, New York, NY
`;

const TERMS_MARKDOWN = `These terms govern your use of **twelvecreative.io**. By using the site you
accept them. If you do not agree with them, please do not use the site.

They cover the website itself. Any project we take on for you is governed by a
separate written agreement, and where the two differ, that agreement wins.

## Who we are

Twelve Creative is a marketing and creative studio based in New York, NY,
contactable at hello@twelvecreative.io.

## Using this site

You may browse the site and use its forms to contact us. You agree not to:

- interfere with the site or try to break its security;
- access areas you are not authorised to access;
- scrape, copy or republish its content at scale without our permission;
- send unlawful, misleading or abusive content through our forms;
- use automated tools to flood our forms.

We rate-limit form submissions and may block access that appears abusive.

## What you send us

You keep ownership of anything you send through our forms. By sending it, you
give us permission to read it, store it and use it to respond to you and to
provide our services.

Please do not send confidential information through the website forms. Use them
to start a conversation; we will agree a secure channel and, if you want one, a
confidentiality agreement before you share anything sensitive.

## Our content

The content on this site — including text, design, layout, graphics, video and
the Twelve Creative name and logo — belongs to us or to our clients and is
protected by intellectual property law.

You may view and share it. You may not reproduce it commercially, present it as
your own, or use our clients' names or marks without written permission.

Case studies and client work shown here remain the property of the respective
client and are published with their permission.

## Enquiries are not a contract

Submitting a booking request or a message does not create a contract, does not
oblige us to take on the work, and does not oblige you to buy anything. Work
begins only when both sides sign a written agreement covering scope, fees and
timelines.

## Availability

We aim to keep the site available and accurate, but we do not guarantee that it
will be uninterrupted or error-free. We may change, suspend or withdraw any part
of it, and we may update these terms — the version published here is the one
that applies.

## Third-party links

The site may link to other websites. We do not control them and are not
responsible for their content, their security or their privacy practices.
Visiting them is at your own risk.

## Disclaimers and liability

The site and its content are provided "as is". Information here is general and
is not professional, financial or legal advice; do not act on it alone.

To the fullest extent permitted by law, we are not liable for indirect or
consequential loss, or for lost profits, revenue, data, goodwill or business
opportunity, arising from your use of the site. Nothing in these terms limits
liability that cannot legally be limited.

## Indemnity

If your misuse of the site, or your breach of these terms, causes a third party
to bring a claim against us, you agree to cover the reasonable costs of dealing
with it.

## Governing law

These terms are governed by the laws of the State of New York, and the courts
of New York have exclusive jurisdiction over any dispute arising from them.

## Contact us

**Email:** hello@twelvecreative.io
**Twelve Creative**, New York, NY
`;

export const LEGAL_PAGE_SEED: TLegalPageInput[] = [
  {
    slug: 'privacy-policy',
    title: 'Privacy Policy',
    markdown: PRIVACY_POLICY_MARKDOWN,
    effective_date: EFFECTIVE_DATE,
    seo: {
      title: 'Privacy Policy | Twelve Creative',
      description:
        'How Twelve Creative collects, uses and protects the information you share through twelvecreative.io. No advertising or analytics tracking.',
    },
    is_published: true,
  },
  {
    slug: 'terms-and-conditions',
    title: 'Terms and Conditions',
    markdown: TERMS_MARKDOWN,
    effective_date: EFFECTIVE_DATE,
    seo: {
      title: 'Terms and Conditions | Twelve Creative',
      description:
        'The terms that govern your use of twelvecreative.io, including acceptable use, intellectual property and liability.',
    },
    is_published: true,
  },
];

export type TLegalPageSeedReport = {
  module: 'legal-pages';
  action: 'inserted' | 'skipped' | 'replaced';
  count: number;
};

export async function seedLegalPages(
  force: boolean,
): Promise<TLegalPageSeedReport> {
  if (force) {
    await LegalPage.deleteMany({});
    await LegalPage.insertMany(LEGAL_PAGE_SEED);
    return {
      module: 'legal-pages',
      action: 'replaced',
      count: LEGAL_PAGE_SEED.length,
    };
  }

  const existing = await LegalPage.find().select('slug -_id').lean();
  const slugs = new Set(existing.map((item) => item.slug));
  const missing = LEGAL_PAGE_SEED.filter((item) => !slugs.has(item.slug));
  if (!missing.length) {
    return {
      module: 'legal-pages',
      action: 'skipped',
      count: LEGAL_PAGE_SEED.length,
    };
  }

  await LegalPage.insertMany(missing);
  return { module: 'legal-pages', action: 'inserted', count: missing.length };
}
